# Project information
site_name: Steam Group Game Club Switzerland
site_url: https://steam.gameclub.ch
site_author: D3lta
site_description: >-
  All Player of the Steam Group Game Club Switzerland

# Theme
theme:
  name: material
  language: de
  features:
    #- navigation.instant
    #- navigation.instant.progress
    #- navigation.tracking
    - navigation.tabs
    #- navigation.tabs.sticky
    #- navigation.sections
    #- navigation.expand
    - navigation.indexes
    #- toc.follow
    #- toc.integrate
    #- navigation.top
    - content.tabs.link
    - content.code.copy
    - content.action.view
    - content.action.edit
    - search.suggest
    - search.highlight
    - search.share

extra_css:
  - https://cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css
  - https://cdn.datatables.net/1.13.6/css/dataTables.bootstrap5.min.css
  - https://cdn.datatables.net/responsive/2.5.0/css/responsive.bootstrap5.min.css

extra_javascript:
  - https://code.jquery.com/jquery-3.7.0.min.js
  - https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js
  - https://cdn.datatables.net/1.13.6/js/dataTables.bootstrap5.min.js
  - https://cdn.datatables.net/responsive/2.5.0/js/dataTables.responsive.min.js
  - https://cdn.datatables.net/responsive/2.5.0/js/responsive.bootstrap5.min.js
  - javascripts/datatables-init.js
  - javascripts/tablesorts.js

plugin:
  - meta
  - search
  - tags

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - tables
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - index.md
  - Games: games.md
  - Player: player.md
  - Groups: groups.md
